### ISSUE TITLE
Underscores in item names

### ISSUE THREAD

**Issue by Classsic36** [Classic36-Media/Silly-Eatables#1]
### What happened?

Crafted items have underscores in their name instead of spaces.

### Version

v1.0.0-beta1

### Minecraft Version

Vanilla, 24w13a

**Comment by Classsic36** [comment]
Removing the underscores makes the item uncraftable for whatever reason. I still consider myself an absolute noob when it comes to data packs, so I have no idea why it does this, especially as it works when using creating the item with a command.

**Comment by DamiansStupidCodeLMAO** [comment]
Hey, I know how to solve this, as it's an issue I've experienced before. 
As stated in [MC-271144](https://bugs.mojang.com/browse/MC-271144), it's a text component, meaning you have to nest your quotes. Basically, add `\"` inside of your existing quotes.
Here's an example from my datapack: `"minecraft:item_name": "\"Sweetened Nether Wart\""`
I hope this helps!

**Comment by Classsic36** [comment]
> Hey, I know how to solve this, as it's an issue I've experienced before. As stated in [MC-271144](https://bugs.mojang.com/browse/MC-271144), it's a text component, meaning you have to nest your quotes. Basically, add `\"` inside of your existing quotes. Here's an example from my datapack: `"minecraft:item_name": "\"Sweetened Nether Wart\""` I hope this helps!

Thank you! Will release an update to fix this shortly!
